org.gradle.jvmargs=-Xmx2048M
org.gradle.java.home=C:/Program Files/Eclipse Adoptium/jdk-21.0.12.101-hotspot
minecraft_version=1.21.11
yarn_mappings=1.21.11+build.6
loader_version=0.19.5
mod_version=1.0.0
maven_group=com.maseffectsplus
archives_base_name=MasEffectsPlus
fabric_version=0.141.6+1.21.11
